name: Semantic release 

on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v16
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install 
      - name: Build app
        run: npm run build 
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
          NPM_TOKEN: ${{ secrets.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 }}
        run: npx semantic-release