name: Semantic release 

on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install 
      - name: Build app
        run: npm run build 
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
          NPM_TOKEN: ${{ secrets.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 }}
        run: npx semantic-release